import bcrypt from "bcryptjs";

const SHOP_DATA = {
  users: [
    {
      name: "Abbas",
      email: "admin@example.com",
      password: bcrypt.hashSync("Abs123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("Abs123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      id: "p1",
      name: "دمپایی",
      price: 146250,
      image: "/images/asset21.jpeg",
      isFeatured: true,
      featuredImage: "/images/slider0.jpeg",
      isPopular: true,
      brand: "Nothing",
      category: "Clothing",
      quantity: 0,
      countInStock: 18,
      isFreeDelivery: true,
      rating: 0,
      numReviews: 0,
    },
    {
      id: "p2",
      name: "کتاب",
      price: 45000,
      image: "/images/asset22.jpeg",
      isFeatured: true,
      featuredImage: "/images/slider1.jpeg",
      isPopular: false,
      brand: "Nothing",
      category: "Entertainment",
      quantity: 0,
      countInStock: 22,
      isFreeDelivery: false,
      rating: 4.3,
      numReviews: 0,
    },
    {
      id: "p3",
      name: "ساعت هوشمند",
      price: 396000,
      image: "/images/asset23.jpeg",
      isPopular: false,
      brand: "Nothing",
      category: "Clothing",
      quantity: 0,
      countInStock: 5,
      isFreeDelivery: false,
      rating: 0,
      numReviews: 0,
    },
    {
      id: "p4",
      name: "پولوشرت",
      price: 159000,
      image: "/images/asset24.jpeg",
      isPopular: true,
      brand: "Lebas",
      category: "Clothing",
      quantity: 0,
      countInStock: 17,
      isFreeDelivery: true,
      rating: 0,
      numReviews: 0,
    },
    {
      id: "p5",
      name: "فرش",
      price: 1250000,
      image: "/images/asset28.jpeg",
      isPopular: false,
      brand: "Nothing",
      category: "Home Appliances",
      quantity: 0,
      countInStock: 4,
      isFreeDelivery: false,
      rating: 0,
      numReviews: 0,
    },
    {
      id: "p6",
      name: "چاقو آشپزخانه",
      price: 318000,
      image: "/images/asset30.jpeg",
      isPopular: true,
      brand: "Nothing",
      category: "Home Appliances",
      quantity: 0,
      countInStock: 12,
      isFreeDelivery: true,
      rating: 0,
      numReviews: 0,
    },
    {
      id: "p7",
      name: "پنکه",
      price: 1850000,
      image: "/images/asset32.jpeg",
      isPopular: false,
      brand: "Nothing",
      category: "Home Appliances",
      quantity: 0,
      countInStock: 10,
      isFreeDelivery: false,
      rating: 0,
      numReviews: 0,
    },
    {
      id: "p8",
      name: "کیف",
      price: 365250,
      image: "/images/asset33.jpeg",
      isPopular: false,
      brand: "Nothing",
      category: "Clothing",
      quantity: 0,
      countInStock: 13,
      isFreeDelivery: true,
      rating: 0,
      numReviews: 0,
    },

    {
      id: "p9",
      name: "شیشه شور",
      price: 23000,
      image: "/images/asset44.jpeg",
      isPopular: true,
      brand: "Nothing",
      category: "Home Appliances",
      quantity: 0,
      countInStock: 0,
      isFreeDelivery: false,
      rating: 0,
      numReviews: 0,
    },
  ],
  sliders: [
    {
      id: "s0",
      title: "slider 0",
      image: "/images/slider0.jpeg",
      url: "/products",
    },
    {
      id: "s1",
      title: "slider 1",
      image: "/images/slider1.jpeg",
      url: "/products",
    },
    {
      id: "s2",
      title: "slider 2",
      image: "/images/slider2.jpeg",
      url: "/products",
    },
    {
      id: "s3",
      title: "slider 3",
      image: "/images/slider3.jpeg",
      url: "/products",
    },
  ],
  province: [
    {
      province: "آذربايجان شرقي",
      city: [
        "اسكو",
        "اهر",
        "ایلخچی",
        "باسمنج",
        "بستان آباد",
        "بناب",
        "تبريز",
        "تسوج",
        "جلفا",
        "خسروشهر",
        "سراب",
        "سهند",
        "شبستر",
        "صوفیان",
        "مراغه",
        "مرند",
        "ملكان",
        "ممقان",
        "ميانه",
        "هاديشهر",
        "هريس",
        "هشترود",
        "ورزقان",
      ],
    },
    {
      province: "آذربايجان غربي",
      city: [
        "اروميه",
        "اشنويه",
        "بوكان",
        "تكاب",
        "خوي",
        "سر دشت",
        "سلماس",
        "شاهين دژ",
        "ماكو",
        "مهاباد",
        "مياندوآب",
        "نقده",
        "پلدشت",
        "پيرانشهر",
        "چالدران",
      ],
    },
    {
      province: "اردبيل",
      city: [
        "اردبيل",
        "خلخال",
        "مشگين شهر",
        "نمين",
        "نير",
        "پارس آباد",
        "گرمي",
      ],
    },
    {
      province: "اصفهان",
      city: [
        "آران و بيدگل",
        "اردستان",
        "اصفهان",
        "باغ بهادران",
        "تودشک",
        "تيران",
        "حاجي آباد",
        "خميني شهر",
        "خوانسار",
        "درچه",
        "دهاقان",
        "زرين شهر",
        "سميرم",
        "شهرضا",
        "عسگران",
        "علويجه",
        "فلاورجان",
        "كاشان",
        "مباركه",
        "نجف آباد",
        "نطنز",
        "ورزنه",
        "کوهپایه",
        "گلپايگان",
      ],
    },
    {
      province: "البرز",
      city: ["اشتهارد", "طالقان", "كرج", "ماهدشت", "نظرآباد", "هشتگرد"],
    },
    {
      province: "ايلام",
      city: [
        "آبدانان",
        "ايلام",
        "ايوان",
        "دره شهر",
        "دهلران",
        "سرابله",
        "مهران",
      ],
    },
    {
      province: "بوشهر",
      city: [
        "اهرم",
        "برازجان",
        "بوشهر",
        "جم",
        "خورموج",
        "دير",
        "عسلویه",
        "كنگان",
        "کاکی",
        "گناوه",
      ],
    },
    {
      province: "تهران",
      city: [
        "اسلامشهر",
        "باقرشهر",
        "بومهن",
        "تجريش",
        "تهران",
        "دماوند",
        "رباط كريم",
        "رودهن",
        "ري",
        "شريف آباد",
        "شهريار",
        "فشم",
        "فيروزكوه",
        "قدس",
        "قرچك",
        "كهريزك",
        "لواسان",
        "ملارد",
        "ورامين",
        "پاكدشت",
        "چهاردانگه",
      ],
    },
    {
      province: "چهارمحال بختياري",
      city: ["اردل", "بروجن", "شهركرد", "فارسان", "لردگان", "چلگرد"],
    },
    {
      province: "خراسان جنوبي",
      city: ["بيرجند", "سربيشه", "فردوس", "قائن", "نهبندان"],
    },
    {
      province: "خراسان رضوي",
      city: [
        "تايباد",
        "تربت جام",
        "تربت حيدريه",
        "خواف",
        "درگز",
        "سبزوار",
        "سرخس",
        "طبس",
        "طرقبه",
        "فريمان",
        "قوچان",
        "كاشمر",
        "مشهد",
        "نيشابور",
        "چناران",
        "گناباد",
      ],
    },
    {
      province: "خراسان شمالي",
      city: ["آشخانه", "اسفراين", "بجنورد", "جاجرم", "شيروان"],
    },
    {
      province: "خوزستان",
      city: [
        "آبادان",
        "انديمشك",
        "اهواز",
        "ايذه",
        "ايرانشهر",
        "باغ ملك",
        "بندر امام خميني",
        "بندر ماهشهر",
        "بهبهان",
        "حمیدیه",
        "خرمشهر",
        "دزفول",
        "رامشیر",
        "رامهرمز",
        "سوسنگرد",
        "شادگان",
        "شادگان",
        "شوش",
        "شوشتر",
        "لالي",
        "مسجد سليمان",
        "ملاثانی",
        "هنديجان",
        "هويزه",
      ],
    },
    {
      province: "زنجان",
      city: ["آب بر", "ابهر", "خدابنده", "خرمدره", "زنجان", "قيدار", "ماهنشان"],
    },
    {
      province: "سمنان",
      city: ["ايوانكي", "بسطام", "دامغان", "سمنان", "شاهرود", "گرمسار"],
    },
    {
      province: "سيستان و بلوچستان",
      city: [
        "ايرانشهر",
        "خاش",
        "زابل",
        "زاهدان",
        "سراوان",
        "سرباز",
        "ميرجاوه",
        "چابهار",
      ],
    },
    {
      province: "فارس",
      city: [
        "آباده",
        "اردكان",
        "ارسنجان",
        "استهبان",
        "اقليد",
        "بوانات",
        "جهرم",
        "حاجي آباد",
        "خرامه",
        "خنج",
        "داراب",
        "زرقان",
        "سروستان",
        "سوريان",
        "سپيدان",
        "شيراز",
        "صفاشهر",
        "فراشبند",
        "فسا",
        "فيروز آباد",
        "كازرون",
        "لار",
        "لامرد",
        "مرودشت",
        "مهر",
        "کوار",
      ],
    },
    { province: "قزوين", city: ["آبيك", "بوئين زهرا", "تاكستان", "قزوين"] },
    { province: "قم", city: ["قم"] },
    {
      province: "كردستان",
      city: [
        "بانه",
        "بيجار",
        "حسن آباد",
        "سقز",
        "سنندج",
        "صلوات آباد",
        "قروه",
        "مريوان",
      ],
    },
    {
      province: "كرمان",
      city: [
        "انار",
        "بافت",
        "بردسير",
        "بم",
        "جيرفت",
        "راور",
        "رفسنجان",
        "زرند",
        "سيرجان",
        "كرمان",
        "كهنوج",
        "کوهبنان",
      ],
    },
    {
      province: "كرمانشاه",
      city: [
        "اسلام آباد غرب",
        "جوانرود",
        "سنقر",
        "صحنه",
        "قصر شيرين",
        "كرمانشاه",
        "كنگاور",
        "هرسين",
        "پاوه",
      ],
    },
    {
      province: "كهكيلويه و بويراحمد",
      city: ["دهدشت", "دوگنبدان", "سي سخت", "ياسوج", "گچساران"],
    },
    {
      province: "گلستان",
      city: [
        "آزاد شهر",
        "آق قلا",
        "راميان",
        "علي آباد كتول",
        "كردكوی",
        "كلاله",
        "گرگان",
        "گنبد كاووس",
      ],
    },
    {
      province: "گيلان",
      city: [
        "آستارا",
        "املش",
        "تالش",
        "رشت",
        "رودبار",
        "شفت",
        "صومعه سرا",
        "فومن",
        "لاهیجان",
        "لنگرود",
        "ماسال",
        "ماسوله",
        "منجيل",
        "هشتپر",
      ],
    },
    {
      province: "لرستان",
      city: [
        "ازنا",
        "الشتر",
        "اليگودرز",
        "بروجرد",
        "خرم آباد",
        "دزفول",
        "دورود",
        "كوهدشت",
        "ماهشهر",
        "نور آباد",
      ],
    },
    {
      province: "مازندران",
      city: [
        "آمل",
        "بابل",
        "بابلسر",
        "بلده",
        "بهشهر",
        "تنكابن",
        "جويبار",
        "رامسر",
        "ساري",
        "قائم شهر",
        "محمود آباد",
        "نكا",
        "نور",
        "نوشهر",
        "چالوس",
      ],
    },
    {
      province: "مركزي",
      city: [
        "آشتيان",
        "اراك",
        "تفرش",
        "خمين",
        "دليجان",
        "ساوه",
        "شازند",
        "محلات",
      ],
    },
    {
      province: "هرمزگان",
      city: [
        "بستك",
        "بندر جاسك",
        "بندر خمیر",
        "بندر لنگه",
        "بندرعباس",
        "حاجي آباد",
        "دهبارز",
        "قشم",
        "قشم",
        "كيش",
        "ميناب",
      ],
    },
    {
      province: "همدان",
      city: ["اسدآباد", "بهار", "رزن", "ملاير", "نهاوند", "همدان"],
    },
    {
      province: "يزد",
      city: [
        "ابركوه",
        "اردكان",
        "اشكذر",
        "بافق",
        "تفت",
        "خضرآباد",
        "زارچ",
        "طبس",
        "مهريز",
        "ميبد",
        "هرات",
        "يزد",
      ],
    },
  ],
};

export const getAllProduct = () => {
  return SHOP_DATA.products;
};

export const getPopularProduct = () => {
  return SHOP_DATA.products.filter((product) => product.isPopular);
};

export const getProductById = (productId) => {
  return SHOP_DATA.products.find((product) => product.id === productId);
};

export const getInCart = () => {
  return SHOP_DATA.products.filter((product) => product.addCart);
};

export const getAllProvince = () => {
  return SHOP_DATA.province;
};

//Slider

export const getAllSlider = () => {
  return SHOP_DATA.sliders;
};

export default SHOP_DATA;
